/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Col: typeof import('./src/components/layout/Col.vue')['default']
    Container: typeof import('./src/components/layout/Container.vue')['default']
    Flex: typeof import('./src/components/layout/Flex.vue')['default']
    LayoutDemo: typeof import('./src/components/layout/LayoutDemo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('./src/components/layout/Row.vue')['default']
    Space: typeof import('./src/components/layout/Space.vue')['default']
  }
}
