/**
 * 样式属性面板配置
 * 包含所有组件共有的样式属性
 */

import { PanelGroup, type PanelConfig } from '../types'
import { FieldType } from '../../fields/types'

/**
 * 样式属性面板
 */
export const StylePanel: PanelConfig = {
  group: PanelGroup.STYLE,
  title: '样式属性',
  icon: 'BgColorsOutlined',
  collapsible: true,
  defaultExpanded: false,
  order: 3,
  fields: [
    {
      key: 'backgroundColor',
      label: '背景颜色',
      type: FieldType.COLOR,
      placeholder: '#ffffff',
      tooltip: '组件的背景颜色',
      layout: { span: 1 },
    },
    {
      key: 'color',
      label: '文字颜色',
      type: FieldType.COLOR,
      placeholder: '#000000',
      tooltip: '组件的文字颜色',
      layout: { span: 1 },
    },
    {
      key: 'fontSize',
      label: '字体大小',
      type: FieldType.SELECT,
      defaultValue: 14,
      tooltip: '文字的字体大小(px)',
      layout: { span: 1 },
      options: [
        { label: '12px', value: 12 },
        { label: '14px', value: 14 },
        { label: '16px', value: 16 },
        { label: '18px', value: 18 },
        { label: '20px', value: 20 },
        { label: '24px', value: 24 },
        { label: '28px', value: 28 },
        { label: '32px', value: 32 },
        { label: '36px', value: 36 },
        { label: '48px', value: 48 },
        { label: '64px', value: 64 },
        { label: '72px', value: 72 },
      ],
    },
    {
      key: 'fontWeight',
      label: '字体粗细',
      type: FieldType.SELECT,
      defaultValue: 'normal',
      tooltip: '文字的粗细程度',
      layout: { span: 1 },
      options: [
        { label: '正常 (normal)', value: 'normal' },
        { label: '粗体 (bold)', value: 'bold' },
        { label: '细体 (lighter)', value: 'lighter' },
        { label: '100', value: '100' },
        { label: '200', value: '200' },
        { label: '300', value: '300' },
        { label: '400', value: '400' },
        { label: '500', value: '500' },
        { label: '600', value: '600' },
        { label: '700', value: '700' },
        { label: '800', value: '800' },
        { label: '900', value: '900' },
      ],
    },
    {
      key: 'textAlign',
      label: '文字对齐',
      type: FieldType.SELECT,
      defaultValue: 'left',
      tooltip: '文字的对齐方式',
      layout: { span: 1 },
      options: [
        { label: '左对齐 (left)', value: 'left' },
        { label: '居中 (center)', value: 'center' },
        { label: '右对齐 (right)', value: 'right' },
        { label: '两端对齐 (justify)', value: 'justify' },
      ],
    },
    {
      key: 'lineHeight',
      label: '行高',
      type: FieldType.TEXT,
      placeholder: '1.5, 24px',
      tooltip: '文字的行高',
      layout: { span: 1 },
    },
    {
      key: 'border',
      label: '边框',
      type: FieldType.TEXT,
      placeholder: '1px solid #ccc',
      tooltip: '组件的边框样式',
      layout: { span: 2 },
      visualizer: {
        type: 'border',
        interactive: true,
        preview: true,
      },
    },
    {
      key: 'borderRadius',
      label: '圆角',
      type: FieldType.TEXT,
      placeholder: '0, 4px, 50%',
      tooltip: '组件的圆角大小',
      layout: { span: 1 },
    },
    {
      key: 'boxShadow',
      label: '阴影',
      type: FieldType.TEXT,
      placeholder: '0 2px 8px rgba(0,0,0,0.15)',
      tooltip: '组件的阴影效果',
      layout: { span: 1 },
    },
    {
      key: 'opacity',
      label: '透明度',
      type: FieldType.SLIDER,
      min: 0,
      max: 1,
      step: 0.1,
      defaultValue: 1,
      tooltip: '组件的透明度(0-1)',
      layout: { span: 2 },
    },
    {
      key: 'cursor',
      label: '鼠标样式',
      type: FieldType.SELECT,
      defaultValue: 'default',
      tooltip: '鼠标悬停时的样式',
      layout: { span: 1 },
      options: [
        { label: '默认 (default)', value: 'default' },
        { label: '指针 (pointer)', value: 'pointer' },
        { label: '文本 (text)', value: 'text' },
        { label: '移动 (move)', value: 'move' },
        { label: '禁止 (not-allowed)', value: 'not-allowed' },
        { label: '等待 (wait)', value: 'wait' },
        { label: '帮助 (help)', value: 'help' },
      ],
    },
    {
      key: 'overflow',
      label: '溢出处理',
      type: FieldType.SELECT,
      defaultValue: 'visible',
      tooltip: '内容溢出时的处理方式',
      layout: { span: 1 },
      options: [
        { label: '可见 (visible)', value: 'visible' },
        { label: '隐藏 (hidden)', value: 'hidden' },
        { label: '滚动 (scroll)', value: 'scroll' },
        { label: '自动 (auto)', value: 'auto' },
      ],
    },
  ],
}
